/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Scanner;
/**
 *
 * @author danpras
 */
public class ScenarioOneUI extends javax.swing.JFrame {
    
    MenuUI menuUI = new MenuUI();    
    int choice;
    int effect1A;
    int effect1B;
    int effect1C;
    int effect2A;
    int effect2B;
    int effect2C;
    int effect3A;
    int effect3B;
    int effect3C;
    int end1;
    /**
     * Creates new form ScenarioOneUI
     */
    public ScenarioOneUI() {
        initComponents();
                     
        
        labelScript.setText("<HTML>Narrator: In the mountains, far from civilization, "
                + "lays a lone temple. Within the temple, " 
                + "dozens of students are training daily, learning in"
                + " the ways of Kung Fu.<BR> It's early morning as " + MenuUI.name
                + " heads to the training field for dailly sparring.</HTML>");
        
        labelPrompt.setText("<HTML><b>Master Yon:</b> A good morning to you, young " + MenuUI.name + ".<BR>"
                          + "<b>" +MenuUI.name + ":</b> *bows* You as well, Master Yon." + "<BR>"
                          + "<b>Master Yon:</b> Are you prepared, young " + MenuUI.name + "?<BR>"
                          + "<b>" +MenuUI.name + ":</b> Yes Master. I am ready." + "<BR>" + "<BR>"
                          + "Preparing " + MenuUI.himselfHerself() + " for a fight, " + MenuUI.name + " moves to a...");
                                  
        labelDesc1.setText("Offensive stance");
        labelDesc2.setText("Defensive stance");
        //labelDesc3.setText("Neutral stance");
        
        
        button3.setVisible(false);
        labelDesc3.setVisible(false);
    }    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelScript = new javax.swing.JLabel();
        labelPrompt = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        labelDesc1 = new javax.swing.JLabel();
        labelDesc2 = new javax.swing.JLabel();
        labelDesc3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelScript.setText("Script");

        labelPrompt.setText("Choice Prompt");

        button1.setText("1.");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setText("2.");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setText("3.");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        labelDesc1.setText("Description 1");

        labelDesc2.setText("Description 2");

        labelDesc3.setText("Description 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelScript)
                    .addComponent(labelPrompt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(button3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDesc3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(button2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDesc2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(button1)
                            .addGap(28, 28, 28)
                            .addComponent(labelDesc1))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelScript)
                .addGap(36, 36, 36)
                .addComponent(labelPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1)
                    .addComponent(labelDesc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button2)
                    .addComponent(labelDesc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button3)
                    .addComponent(labelDesc3))
                .addGap(77, 77, 77))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        switch(choice)
        {
            case 0: 
                labelScript.setText("<HTML>" + MenuUI.name + " rushes forward, kicking off"
                            + " the ball of their left foot. Raising their right foot"
        + ", poised to attack, " + MenuUI.name + " goes for a kick to the head, "
        + "only to find themselves on the ground, looking towards the open sky.");
                
        labelPrompt.setText("<HTML><b>Master Yon:</b> Once again, you never learn. Always rushing headfirst " 
                          + "without using your head. " + "<BR>"
                          + "<b>" + MenuUI.name + ":</b> *bows head* I understand Master Yon." + "<BR>"
                          + "<b>Master Yon:</b> *sighs* And yet you fail to learn. Your time will come when you will be forced "
                          + "to fight. Let us hope that you can learn by then.<BR>"
                          + "<b>Master Yon:</b> " + " You are strong " + MenuUI.name + ", but you need to learn self-control." + "<BR>" + "<BR>");
       
        
        labelDesc1.setText("Continue");
        button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
        choice++;
        effect1A = 1;        
        break;
                
            case 1: 
         labelScript.setText("<HTML>Weeks passed as " + MenuUI.name + " continued to train both body and mind. " 
                            + "Meditation and physical training became a daily routine. It had been seven years <BR>"
                            + "since " + MenuUI.name + " first arrived at the temple. Training day after day, " 
                            + MenuUI.name + " got stronger. Smarter. Training the abilities of the body and mind to <BR>"
                            + "achieve " + MenuUI.genderHis + " goal. Becoming a Martial Arts Master. There was no " 
                            + " belt color to determine one's rank. Your skill showed that. " + MenuUI.name + " had" 
                            + " rumors about certain trials you passed to become a Master. Many students had tried over the years,"
                            + " only four had ever emerged victoroius. Master Ti-Lun, Master Chena, and Master Yon. " 
                            + MenuUI.name + " had always looked up to " + MenuUI.himHer() + " Masters, and strived to be just like them.");
          labelPrompt.setText("");
          button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
         choice++;
         break;
         
            case 2:
                labelScript.setText("<HTML>As time passed, " + MenuUI.name + " noticed that things were speeding up in the temple. "
                            + " The lessons and the training were becoming more frequent and more obscure. The lessons became less "
                            + " clear and more diffucult to fully comprehend. Training felt less vigorous and more tense, like they "
                            + " were preparing for something. During " + MenuUI.name + "'s lessons with Master Ti-Lun, " + MenuUI.name 
                            + " was asked a startling question.");
                labelPrompt.setText("<HTML><b>Master Ti-Lun:</b> Tell me " + MenuUI.name + ", have you ever killed before?<BR>" +
                                    "<b>" + MenuUI.name + ":</b> I... never, I've kiled animals before, but never a human being.<BR>" +
                                    "<b>Master Ti-Lun:</b> I see. A life is still a life. We stick to our morals. Never take a life. If we do, then we are" +
                                    " no better than our enemy. Life is an infinite cycle, and that must be cherished." + "<BR>" + "<BR>" +
                                    " So " + MenuUI.name + ", would you take a life?");
                button2.setVisible(true);
                labelDesc2.setVisible(true);
                button3.setVisible(true);
                labelDesc3.setVisible(true);
                if(effect1A == 1)
                {
                labelDesc1.setText("Yes, without question.");
                labelDesc2.setText("I hope I never have to make that decision.");
                labelDesc3.setText("No. It is not our right to take a life.");
                }
                else
                {
                labelDesc1.setText("Only if I had to.");
                labelDesc2.setText("I hope I never have to make that decision.");
                labelDesc3.setText("No. It is not our right to take a life.");
                }
                choice++;
                
                break;
            case 3:
                               
                if(effect1A == 1)   
                {
                    labelScript.setText("Master Ti-Lun appears to be revolted with " + MenuUI.name + "'s answer. ");
                    labelPrompt.setText("<HTML><b>Master Ti-Lun:</b> I see Master Yon was wrong about you. He thought you could learn from your mistakes," 
                         + " and continue as a student here in the Temple. However, I see that you lack the mentality to do so. You have the mindset"
                         + " of an unrestrained beast. Always eager to fight, always holding an anger inside you. And now you say you would take life?<BR>"
                         + "<b>Master Ti-Lun:</b> I see that throughout your time here, you have learned nothing. And so you shall have nothing. As of today, you, "
                         + MenuUI.name + " are a disgrace to the Martial Arts name. I ban you from this temple for the rest of your miserable life.");
                labelDesc1.setText("Continue");
                effect2A = 1;
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
                }
                
                else 
                {
                labelScript.setText("Master Ti-Lun dissaproves of " + MenuUI.name + "'s answer. ");
                labelPrompt.setText("<HTML><b>Master Ti-Lun:</b> *sighs* I had hoped that you would see differently. Several students had similar views as you "
                + "did, all of them seeing Kung Fu as a way of aquiring power. They believed learning Martial Arts would guide them to strength in life. All of them are "
                + "no longer students here. You would have been banished from the temple, but Master Yon believes in you, and that is something I do not take lightly. "
                + "This is your last chance to prove yourself, you will be allowed to stay as a student, but should you stray from our ways again, you will not be allowed to stay here. Understood?");                                   
                       
                       
                labelDesc1.setText("Yes Master Ti-Lun.");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
                }
                
                choice++;           
                break;               
                           
            case 4:
                if(effect2A == 1)   
                {
                labelScript.setText("<HTML>Escorted to " + MenuUI.hisHer() + " quarters, " + MenuUI.name + " packed up what little things " + MenuUI.heShe()
                + " had. " + MenuUI.name + " opened the doors to the main entrance to the temple, and took " + MenuUI.hisHer() + " first steps outide the temple"
                + " for the first time in seven years. It is unclear what happened to " + MenuUI.name + " afterwards, but " + MenuUI.heShe() + " never returned to the temple, ever again."
                + "<BR>" + "<BR>End");
                labelPrompt.setText("");
                end1 = 1;
                labelDesc1.setText("End");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false); 
                }
                else
                {
                labelScript.setText("<HTML>After Master Ti-Lun's lesson, " + MenuUI.name + " left to calm " + MenuUI.himselfHerself() + " with meditation. "
                + " Wandering off to the garden, " + MenuUI.name + " knelt in a clearing, trying to clear " + MenuUI.hisHer() + " mind.");
                labelPrompt.setText(" ");
                }
                labelDesc1.setText("Continue");
                choice++;
            break;
            case 5:
                if(end1 == 1)
                {
                this.dispose();
                new MenuUI().setVisible(true);
                }
                else
                {
                labelScript.setText("<HTML>As " + MenuUI.name + " meditated, " + MenuUI.heShe() + " sensed a disturbance in the air. As" + MenuUI.name 
                        + " tilted " + MenuUI.hisHer() + " head slightly to the left, a whistling noise cut through the silence. " + MenuUI.name + "'s eyes shot open, and "
                + "threw " + MenuUI.hisHer() + " body forward, into a roll. The object missed " + MenuUI.name + ", planted itself inside a stone pillar behind " + MenuUI.himHer() + "."
                + " A figure stepped out from behind a tall tree, revealing it to be Master Chena. ");
                
                labelPrompt.setText("<HTML><b>Master Chena:</b> Your reflexes are as sharp as ever. Good, someone needs to keep you on your toes.<BR>"
                + "<b>" + MenuUI.name + ":</b> *chuckles* It's always diffucult to spot you, Master.<BR>"
                + "<b>Master Chena:</b> It's what I aim for. But that's not why I'm here. ");
                labelDesc1.setText("Continue");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
                choice++;
                }
                break;
            case 6:
                labelScript.setText("<HTML>Master Chena turns her back to " + MenuUI.name + ", reaching for something within her robes. Suddenly, using her left hand, she throws a wooden scroll at " + MenuUI.name
                + ", aimed for the head. ");
                labelPrompt.setText("<HTML>" + MenuUI.name + " quickly decides to...");
                labelDesc1.setText("Jump to the left");
                labelDesc2.setText("Side-step to the right");
                button2.setVisible(true);
                labelDesc2.setVisible(true);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
                choice++;
                break;
            case 7:
                
                labelScript.setText("<HTML>" + MenuUI.name + " jumps to " + MenuUI.hisHer() + " left, in hopes of dodging the flying scroll."
                + " However, Master Chena's throw was more curved than " + MenuUI.heShe() + " expected, and the scroll hit " + MenuUI.name + " in the head."
                + " The impact shocked " + MenuUI.name + ", and set " + MenuUI.himHer() + " stumbling backwards, only for " + MenuUI.hisHer() + " to hit the stone pillar behind " + MenuUI.himHer() + ". ");
               
                labelPrompt.setText("<HTML><b>Master Chena:</b> How disapointing, I would have expected you to see that coming. I'm sorry you hit your head, you may have a concussion. I came here to give you a final test, "
                + "but I seem to have injured you instead. Your mind is clearly not in the right place. You would've been offered to begin the trials to become a Master. For now, you'll remain a student and continue your training, but one day. One day you'll be "
                + "offered again to become a Master, but I'm afraid that will have to wait.");
                
                
                labelDesc1.setText("Continue");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
                effect3A = 1;
                choice++;
                break;
            case 8:               
                if(effect3A == 1)
                {
                labelScript.setText("<HTML>Sighing in disapointment, " + MenuUI.name + " respectfully said " + MenuUI.hisHer() + " goodbyes to Master Chena. Returning to "
                + MenuUI.hisHer() + " quarters, " + MenuUI.name + " vowed to be better, and hoped one day, " + MenuUI.heShe() + " would become a Master of Kung Fu. ");
                labelPrompt.setText("End");
                }
                else
                {
                labelScript.setText("");
                labelPrompt.setText("<HTML>Narrator: " + MenuUI.name + " accepted the offer, and would soon begin " + MenuUI.hisHer() + " trials. Training and mental strength would be "
                + "tested like never before. Whether " + MenuUI.name + " suceeded or not, is a story for another day." + "<BR>" + "<BR>End");
                }
                choice++;
                labelDesc1.setText("End");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
                break;
            case 9:
               
                this.dispose();
                new MenuUI().setVisible(true);
                
                break;
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        switch(choice)
        {
         case 0: 
        labelScript.setText("<HTML>" + MenuUI.name + " crosses their arms, blocking a swift kick to the ribs"
                            + " Standing their ground, " + MenuUI.name + " pushes upward, lifting Master Yon's foot into "
                                    + "the open air, before twisting backwards and kicking out at Master Yu. "
        + "The two draw blows before Master Yu lowers his arms, coming to a stop. " + MenuUI.name + " comes to attention, "
        + "bowing at Master Yon.");
        
        labelPrompt.setText("<HTML><b>Master Yon:</b> I see you haven't become completely reckless. " 
                            + "It isn't all about attacking and winning. Analyze your opponent, "
                            + "see the chinks in the armor, and be patient. Without a planned attack, you can never win. " + "<BR>"
                            +"<b>" + MenuUI.name + ":</b> I understand Master, yet I do not. Why fight if you can not win?" + "<BR>"
                            + "<b>Master Yon:</b> It isn't always about winning or losing. "
                            + "Just surviving, can make a difference. Survival is what keeps us alive.");
                            
        
        labelDesc1.setText("Continue");
        button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
        effect1B = 1;
        choice++;
        
        break;
        
         case 1: 
         labelScript.setText("<HTML>Weeks passed as " + MenuUI.name + " continued to train both body and mind. " 
                            + "Meditation and physical training became a daily routine. It had been seven years <BR>"
                            + "since " + MenuUI.name + " first arrived at the temple. Training day after day, " 
                            + MenuUI.name + " got stronger. Smarter. Training the abilities of the body and mind to <BR>"
                            + "achieve " + MenuUI.genderHis + " goal. Becoming a Martial Arts Master. There was no " 
                            + " belt color to determine one's rank. Your skill showed that. " + MenuUI.name + " had" 
                            + " rumors about certain trials you passed to become a Master. Many students had tried over the years,"
                            + " only four had ever emerged victoroius. Master Ti-Lun, Master Chena, and Master  Yon. " 
                            + MenuUI.heShe() + " had always looked up to " + MenuUI.hisHer() + " Masters, and strived to be just like them.");
         
         labelPrompt.setText("");
          button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
         choice++;
         break;
        
         case 2:
             labelScript.setText("<HTML>As time passed, " + MenuUI.name + " noticed that things were speeding up in the temple. "
                            + " The lessons and the training were becoming more frequent and more obscure. The lessons became less "
                            + " clear and more diffucult to fully comprehend. Training felt less vigorous and more tense, like they "
                            + " were preparing for something. During " + MenuUI.name + "'s lessons with Master Ti-Lun, " + MenuUI.name 
                            + " was asked a startling question.");
                labelPrompt.setText("<HTML><b>Master Ti-Lun:</b> Tell me " + MenuUI.name + ", have you ever killed before?<BR>" +
                                    MenuUI.name + ": I... never, I've kiled animals before, but never a human being.<BR>" +
                                    "<b>Master Ti-Lun:</b> I see. A life is still a life. A tree is no more living than me. A bird" +
                                    " is no more living that you. We stick to our morals. Never take a life. If we do, then we are" +
                                    " no better than our enemy. Life is an infinite cycle, and that must be cherished." + "<BR>" + "<BR>" +
                                    " So " + MenuUI.name + ", would you take a life?");
            button2.setVisible(true);
                labelDesc2.setVisible(true);
                button3.setVisible(true);
                labelDesc3.setVisible(true);
               if(effect1A == 1)
                {
                labelDesc1.setText("Yes, without question.");
                labelDesc2.setText("I hope I never have to make that decision.");
                labelDesc3.setText("No. It is not our right to take a life.");
                }
                else
                {
                labelDesc1.setText("Only if I had to.");
                labelDesc2.setText("I hope I never have to make that decision.");
                labelDesc3.setText("No. It is not our right to take a life.");
                }
                
                choice++;
                effect2B = 1;
             break;
             
         case 3:            
                // button1ActionPerformed(evt); //this is the call for the other button to execute it
             
             labelScript.setText("<HTML>Master Ti-Lun seems dissapointed in your response. 'Then you are either a fool or a"
                                + " coward. You must be ready to make your choice, to spare a life or to end one. Not"
                                + " picking a choice says that you are too weak, or you are too cowardly to fight for yourself.'"
                                + " ");
             labelPrompt.setText("");
            labelDesc1.setText("Continue");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
             choice++;
             break;
             
         case 7:
              labelScript.setText("<HTML>" + MenuUI.name + " shifts right, narrowly dodging the flying object sent at " + MenuUI.himHer()
              + ". The object flew past " + MenuUI.himHer() + ", sticking inside the stone pillar, next to the previous object Master Chang had thrown."
              + " Looking back, " + MenuUI.name + " noticed it was a scroll. Master Chena, noticing his " + MenuUI.himHer() + " confusion, motioned"
              + " him to go to it. Picking up the scroll, " + MenuUI.name + " began to read.");
              
              labelPrompt.setText("<HTML><b>" + MenuUI.name + ":</b> Hello " + MenuUI.name + ", we have noticed your potential, and we have seen that it "
              + "has done splendedly. We offer you this chance to do your trials to become a Master. As you are currently reading, there are only three "
              + "Masters on the council. We would like to invite you, should you wish, to begin your trials to becoming a King Fu Master. However, failure "
              + "during your trials will result in a permanant prohibition of the rank of Master, or possibly the permanent banning of your position as a student."
              + " If you believe yourself ready, you will be allowed to begin your trials. If not, and you think you are not "
              + "ready, then you will have four months before your answer is due. Good day, and live in peace, young grasshopper. - Master Yon.");
                labelDesc1.setText("Accept");
                button2.setVisible(true);
                labelDesc2.setText("Decline");
                button3.setVisible(false);
                labelDesc3.setVisible(false);
             choice++;
             break;
         case 8:
             labelScript.setText("");
             
             labelPrompt.setText("<HTML>Narrator: " + MenuUI.name + " declined the offer, and would continue to train " + MenuUI.himselfHerself() 
             + "until " + MenuUI.heShe() + " was offered again. Whether or not she accepted, or declined a second time, is unknown." + "<BR>" + "<BR>End");
                labelDesc1.setText("End");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
             break;
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        switch(choice)
        {
        case 1: 
         labelScript.setText("<HTML>Weeks passed as " + MenuUI.name + " continued to train both body and mind. " 
                            + "Meditation and physical training became a daily routine. It had been seven years <BR>"
                            + "since " + MenuUI.name + " first arrived at the temple. Training day after day, " 
                            + MenuUI.name + " got stronger. Smarter. Training the abilities of the body and mind to <BR>"
                            + "achieve " + MenuUI.genderHis + " goal. Becoming a Martial Arts Master. There was no " 
                            + " belt color to determine one's rank. Your skill showed that. " + MenuUI.name + " had" 
                            + " rumors about certain trials you passed to become a Master. Many students had tried over the years,"
                            + " only four had ever emerged victoroius. Master Ti-Lun, Master Chena and Master Yon. " 
                            + MenuUI.heShe() + " had always looked up to " + MenuUI.himHer() + " Masters, and strived to be just like them.");
          
         labelPrompt.setText("");
         button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
         choice++;
         break;
        
         case 2:
             labelScript.setText("<HTML>As time passed, " + MenuUI.name + " noticed that things were speeding up in the temple. "
                            + " The lessons and the training were becoming more frequent and more obscure. The lessons became less "
                            + " clear and more diffucult to fully comprehend. Training felt less vigorous and more tense, like they "
                            + " were preparing for something. During " + MenuUI.name + "'s lessons with Master Ti-Lun, " + MenuUI.name 
                            + " was asked a startling question.");
                labelPrompt.setText("<HTML><b>Master Ti-Lun:</b> Tell me " + MenuUI.name + ", have you ever killed before?<BR>" +
                                    "<b>" + MenuUI.name + ":</b> I... never, I've kiled animals before, but never a human being.<BR>" +
                                    "<b>Master Ti-Lun:</b> I see. A life is still a life. A tree is no more living than me. A bird" +
                                    " is no more living that you. We stick to our morals. Never take a life. If we do, then we are" +
                                    " no better than our enemy. Life is an infinite cycle, and that must be cherished." + "<BR>" + "<BR>" +
                                    " So " + MenuUI.name + ", would you take a life?");
            
               if(effect1A == 1)
                {
                labelDesc1.setText("Yes, without question.");
                labelDesc2.setText("I hope I never have to make that decision.");
                labelDesc3.setText("No. It is not our right to take a life.");
                }
                else
                {
                labelDesc1.setText("Only if I had to.");
                labelDesc2.setText("I hope I never have to make that decision.");
                labelDesc3.setText("No. It is not our right to take a life.");
                }
                choice++;                
                effect2C++;
             break;
             
         case 3:
             labelScript.setText("Master Ti-Lun seems to approve of your desicion. ");
             if(effect1A == 1)
             {
                 labelPrompt.setText("<HTML><b>Master Ti-Lun:</b> It is a naive ideal, but it is one we are sworn to follow <BR>"
                            + "<b>Master Ti-Lun:</b> Our ways are beginning to fade. Few still follow our ways, most are always looking"
                            + " for a fight they can not win. Just as I heard from Yon, making the first move, albiet quite recklessly.");
             }
             else
             {
                 labelPrompt.setText("<HTML><b>Master Ti-Lun:</b> It is a naive ideal, but it is one we are sworn to follow <BR>"
                            + "<b>Master Ti-Lun:</b> Our ways are beginning to fade. Few still follow our ways, most are always looking"
                            + " for a fight they can not win. However, I heard from Yon that you restrained yourself. Quite an improvement from when you first started here.");
             }
                choice++;
                labelDesc1.setText("Continue");
                button2.setVisible(false);
                labelDesc2.setVisible(false);
                button3.setVisible(false);
                labelDesc3.setVisible(false);
             break;            
                      
        }
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScenarioOneUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScenarioOneUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScenarioOneUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScenarioOneUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScenarioOneUI().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JLabel labelDesc1;
    private javax.swing.JLabel labelDesc2;
    private javax.swing.JLabel labelDesc3;
    private javax.swing.JLabel labelPrompt;
    private javax.swing.JLabel labelScript;
    // End of variables declaration//GEN-END:variables
}
